//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRm.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMARTRMEntities : DbContext
    {
        public SMARTRMEntities()
            : base("name=SMARTRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_deviceRegistration> tbl_deviceRegistration { get; set; }
        public virtual DbSet<tbl_dishes> tbl_dishes { get; set; }
        public virtual DbSet<tbl_dishesType> tbl_dishesType { get; set; }
        public virtual DbSet<tbl_floor> tbl_floor { get; set; }
        public virtual DbSet<tbl_invoice> tbl_invoice { get; set; }
        public virtual DbSet<tbl_invoiceDetail> tbl_invoiceDetail { get; set; }
        public virtual DbSet<tbl_order> tbl_order { get; set; }
        public virtual DbSet<tbl_orderDetail> tbl_orderDetail { get; set; }
        public virtual DbSet<tbl_table> tbl_table { get; set; }
        public virtual DbSet<tbl_tableType> tbl_tableType { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
