//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRm.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_invoice()
        {
            this.tbl_invoiceDetail = new HashSet<tbl_invoiceDetail>();
        }
    
        public System.Guid id { get; set; }
        public string code { get; set; }
        public System.Guid table_id { get; set; }
        public System.Guid user_id { get; set; }
        public string time_in { get; set; }
        public string time_out { get; set; }
        public string date { get; set; }
    
        public virtual tbl_table tbl_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_invoiceDetail> tbl_invoiceDetail { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
