//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRm.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orderDetail
    {
        public System.Guid order_id { get; set; }
        public System.Guid dishes_id { get; set; }
        public int amout { get; set; }
    
        public virtual tbl_dishes tbl_dishes { get; set; }
        public virtual tbl_order tbl_order { get; set; }
    }
}
