//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRm.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dishes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_dishes()
        {
            this.tbl_invoiceDetail = new HashSet<tbl_invoiceDetail>();
            this.tbl_orderDetail = new HashSet<tbl_orderDetail>();
        }
    
        public System.Guid id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public System.Guid type_id { get; set; }
        public string unit { get; set; }
        public string price { get; set; }
        public string description { get; set; }
        public string image { get; set; }
    
        public virtual tbl_dishesType tbl_dishesType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_invoiceDetail> tbl_invoiceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_orderDetail> tbl_orderDetail { get; set; }
    }
}
