//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRm.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoiceDetail
    {
        public System.Guid invoice_id { get; set; }
        public System.Guid dishes_id { get; set; }
        public int amount { get; set; }
    
        public virtual tbl_dishes tbl_dishes { get; set; }
        public virtual tbl_invoice tbl_invoice { get; set; }
    }
}
